version: '3.4'

services:    
  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
    networks:
      - backtier
    volumes:
      - influxdb:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - backtier
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
      
volumes: 
  influxdb:
    driver: local
  grafana:
    driver: local

networks:
  backtier:
    external:
      name: infrastructure_healthcareclaims_net_backtier